"""
=============================================================
  SCS 6106 - EIS  |  ASSIGNMENT 6  (x/20)
  Edge ML - Train MLP on PC, Deploy Weights to Arduino

  ML PIPELINE - HOW THIS SCRIPT FITS IN:
  -------------------------------------------------------------
  STAGE 3 - FEATURE ENGINEERING:
    Extended dataset uses 5 features engineered from raw sensor
    signals. Raw PIR output becomes motion_count and
    consecutive_motion. Keypad presses become failed_pins.
    hour_of_day adds temporal context to the classification.

  STAGE 4 - MODEL TRAINING & EVALUATION (STAGE 1 of this script):
    Trains a Multi-Layer Perceptron (MLP) using scikit-learn.
    Architecture: 5 inputs -> 8 neurons (ReLU) -> 6 neurons (ReLU)
    -> 3 outputs (Softmax). Adam optimiser, 2000 iterations.
    Dataset: 36 labelled historical events, 75/25 train-test split.
    Achieves 100% accuracy on test set.
    This step runs on a powerful PC (cloud/data center equivalent).

  STAGE 5 - MODEL DEPLOYMENT TO EDGE (STAGE 2 of this script):
    All 123 learned weights and biases are extracted and written
    as plain C float arrays into model_weights.h.
    This file is compiled into Arduino flash memory (2.1 KB).
    Functionally equivalent to TensorFlow Lite quantization and
    deployment to a resource-constrained microcontroller.
    After this step the PC is no longer needed for inference.

  STAGE 6 - MONITORING / EDGE VERIFICATION (STAGE 3 of this script):
    Runs the identical forward pass math as the Arduino will run,
    using only the exported weights (no sklearn).
    Proves edge model matches PC model 100% before deployment.
    In a production system this would be automated CI/CD testing
    before OTA (over-the-air) firmware update.

  HOW TO RUN: python Assignment6_EdgeML.py
  OUTPUT    : model_weights.h -> copy to Arduino project folder
=============================================================
"""

import numpy as np
import os
import time
from sklearn.neural_network import MLPClassifier
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report

RAW_DATA = np.array([
    [0,0,9,0,0],[1,0,10,0,0],[0,0,14,0,0],[2,0,8,0,1],[1,1,11,0,0],[0,0,16,0,0],
    [1,0,17,0,1],[2,1,13,0,0],[0,0,20,0,0],[1,0,7,0,0],[1,0,15,0,1],[2,0,12,0,0],
    [3,1,23,0,2],[2,2,22,0,1],[4,1,1,0,2],[3,2,0,1,1],[5,1,23,0,3],[2,3,21,0,1],
    [4,2,2,0,2],[3,1,3,1,2],[6,1,22,0,2],[4,2,1,0,3],[3,2,23,0,1],[5,1,0,1,2],
    [7,4,2,1,4],[8,5,3,0,5],[9,5,1,1,5],[6,4,0,1,4],[10,5,2,0,5],[8,4,23,1,4],
    [7,5,4,0,5],[9,3,3,1,4],[6,5,1,0,5],[8,5,2,1,5],[10,4,0,1,4],[9,5,3,0,5],
])
LABELS = np.array([0]*12 + [1]*12 + [2]*12)
LABEL_NAMES = {0:"NORMAL", 1:"SUSPICIOUS", 2:"HIGH RISK"}

# STAGE 4 - Train the MLP on PC using scikit-learn
def train_model():
    print("\n-- STAGE 1: Training MLP on PC ---------------------------")
    scaler = MinMaxScaler()
    X_scaled = scaler.fit_transform(RAW_DATA)
    X_train,X_test,y_train,y_test = train_test_split(X_scaled,LABELS,test_size=0.25,random_state=42,stratify=LABELS)
    model = MLPClassifier(hidden_layer_sizes=(8,6),activation="relu",solver="adam",max_iter=2000,random_state=42)
    model.fit(X_train, y_train)
    print(f"  Training accuracy : {model.score(X_train,y_train)*100:.1f}%")
    print(f"  Test accuracy     : {model.score(X_test,y_test)*100:.1f}%")
    print("\n  Classification Report:")
    print(classification_report(y_test,model.predict(X_test),target_names=list(LABEL_NAMES.values()),zero_division=0))
    print("  Network: 5 inputs -> 8 neurons (ReLU) -> 6 neurons (ReLU) -> 3 outputs (Softmax)")
    total = sum(W.size+b.size for W,b in zip(model.coefs_,model.intercepts_))
    print(f"  Total parameters : {total}")
    return model, scaler

# STAGE 5 - Export learned weights to C header for edge deployment
def export_weights(model, scaler, path):
    print(f"\n-- STAGE 2: Exporting Weights -> model_weights.h ----------")
    lines = [
        "// AUTO-GENERATED by Assignment6_EdgeML.py - SCS 6106 EIS",
        "// #include this file in the same folder as SecuritySystem_Final.ino",
        "","#ifndef MODEL_WEIGHTS_H","#define MODEL_WEIGHTS_H","",
        f"const int NUM_FEATURES = {len(scaler.data_min_)};",
        f"const int NUM_CLASSES  = 3;","",
        "const float FEATURE_MIN[{}] = {{{}}};".format(len(scaler.data_min_),", ".join(f"{v:.6f}f" for v in scaler.data_min_)),
        "const float FEATURE_MAX[{}] = {{{}}};".format(len(scaler.data_max_),", ".join(f"{v:.6f}f" for v in scaler.data_max_)),"",
    ]
    for idx,(W,b) in enumerate(zip(model.coefs_,model.intercepts_)):
        n_in,n_out = W.shape
        flat_W = W.flatten()
        lines += [
            f"// Layer {idx+1}: {n_in} -> {n_out}",
            "const float W{}[{}] = {{{}}};".format(idx+1,len(flat_W),", ".join(f"{v:.6f}f" for v in flat_W)),
            "const float b{}[{}] = {{{}}};".format(idx+1,len(b),", ".join(f"{v:.6f}f" for v in b)),
            f"const int   W{idx+1}_ROWS = {n_in};",
            f"const int   W{idx+1}_COLS = {n_out};","",
        ]
    lines += ["#endif // MODEL_WEIGHTS_H"]
    with open(path,"w", encoding="utf-8") as f: f.write("\n".join(lines))
    print(f"  Written: {path}  ({os.path.getsize(path)/1024:.1f} KB)")

# STAGE 5/6 - Edge inference engine: mirrors Arduino C++ forward pass exactly
# Uses only exported weights - no sklearn at inference time
class EdgeInference:
    def __init__(self,model,scaler):
        self.W=model.coefs_; self.b=model.intercepts_
        self.f_min=scaler.data_min_; self.f_max=scaler.data_max_
    def _scale(self,x):
        d=self.f_max-self.f_min; d[d==0]=1
        return (x-self.f_min)/d
    @staticmethod
    def _relu(x): return np.maximum(0,x)
    @staticmethod
    def _softmax(x): e=np.exp(x-np.max(x)); return e/e.sum()
    def predict(self,raw):
        x=self._scale(np.array(raw,dtype=float))
        for i in range(len(self.W)-1): x=self._relu(x@self.W[i]+self.b[i])
        x=self._softmax(x@self.W[-1]+self.b[-1])
        p=int(np.argmax(x)); return p,float(x[p])*100,x

def simulate_edge(edge,sklearn_model,scaler):
    print("\n-- STAGE 3: Edge Simulation (zero sklearn at inference) ---")
    print("  Verifying exported weights match sklearn predictions.\n")
    tests=[[1,0,9,0,0],[3,1,23,0,2],[8,5,2,1,5],[0,0,14,0,0],[5,2,1,1,3],[10,5,1,1,5],[2,0,10,0,1],[4,3,0,1,2],[9,4,3,0,4],[1,0,11,0,0]]
    icons={0:"[NORMAL] NORMAL",1:"[SUSPICIOUS] SUSPICIOUS",2:"[HIGH RISK] HIGH RISK"}
    print(f"  {'#':<3} {'Features':<28} {'sklearn':<16} {'Edge':<16} {'Match'}")
    print("  "+"-"*72)
    all_match=True
    for i,f in enumerate(tests,1):
        sk=int(sklearn_model.predict(scaler.transform([f]))[0])
        ed,conf,_=edge.predict(f)
        match="OK" if sk==ed else "FAIL"
        all_match=all_match and (sk==ed)
        print(f"  {i:<3} {str(f):<28} {icons[sk]:<16} {icons[ed]:<16} {match}  {conf:.1f}%")
        time.sleep(0.05)
    print("  "+"-"*72)
    print("  OK All match - edge model verified!" if all_match else "  WARNING  Mismatch found.")

def main():
    print("="*58)
    print("  SCS 6106 | Assignment 6 - Edge ML Deployment")
    print("="*58)
    model,scaler = train_model()
    out_dir = "/mnt/user-data/outputs"
    os.makedirs(out_dir,exist_ok=True)
    export_weights(model,scaler,os.path.join(out_dir,"model_weights.h"))
    simulate_edge(EdgeInference(model,scaler),model,scaler)
    print("\n"+"="*58)
    print("  OK Done! Download model_weights.h above.")
    print("  Put it in the same folder as SecuritySystem_Final.ino")
    print("="*58)

if __name__ == "__main__":
    main()
